before_install:
- gem install bundler
bundler_args: "--verbose"
script: rake test
rvm:
- 2.0.0
- 2.1
- 2.2
- 2.3.1
- ruby-head
gemfile:
- Gemfile
matrix:
  allow_failures:
  - rvm: ruby-head
env: CODECLIMATE_REPO_TOKEN=3733be865016cababd969f8888810daf54fa824d10b126a2fec6123e8a21e2f5
  bundle exec rake
addons:
  code_climate:
    repo_token: 3733be865016cababd969f8888810daf54fa824d10b126a2fec6123e8a21e2f5
deploy:
  provider: rubygems
  api_key:
    secure: g5mnJR1siaBstvvifQVgJZRUcwLYLx5DeLimXMoRBJV2llBiZevSt6Heo4MgvWeNjvh6fRsp5NOhfXKDbLaxS6FLt+5buIMfYBFqJnFjzFoGf4PZj8Zd0XA3SGW82SGfFaHJepykGN7Jx9sOXwEBsbdEbssfiYqvm/uhpew7cAv5le9V3SVLqLsQnN5NwFkbgdHgrD2z1IkOhudkt2b9VZygg8Hj8WimLXq39+bc6eDz1xOV/q9N87r0lnZZqWI2HEL7MAA0pNkX3F8ca27BIe+VSQ9rNCYCmDrzHFpU3R+XjvjlVuv6i5lpQhRZBZCeOSI4/v69PQSosAovC5fIthW2h4XeS2XYHnYszeZKKwbfab8rjt9Mw6fWH3Y3FSMcvKAMNwuTpTYAVDvqLalfpzirryqT/a7Lwi2Hg2LqdoYuhoFrMP8q3vjB+LhxX+4tmTJI/2lt4LaR2HsKRSTZrgGWIr7re57onsSlZIcAXHdmIyXCuh5O9zHn2Bbv4XpAoyVUi7hDmR64oNncn3zTFGOyu6na2BnImoI/mQLm/BxnsQjeaYlV20MPA+Y5kXRhkIyaZzktjsQ+91JRp0JXzxl+cn1ozT1kVsGG8pFNJ0iXKRzy3/Xfcs0OAx6S0nCc7kVyUM2gV6BYvpADoQPm+Uquv7gC0zfjTWW08BBfERA=
  gemspec: inprovise-fork.gemspec
  on:
    tags: true
    repo: mcorino/Inprovise-Fork
